### ISSUE TITLE
NetBox 3 support

### ISSUE THREAD

**Issue by DonMusto** [marcus-crane/netbox-plugin-azuread#2]
I've noticed some editing done - is this plugin going to be brought up to speed to support Netbox 3?

Thanks!

**Comment by marcus-crane** [comment]
Hey @DonMusto,

I hope you've been able to resolve your issue but if not, I just shipped some debug logging in v1.1.1 to try and help narrow down what might be going wrong. You can enable it by setting `LOGLEVEL=DEBUG` in your Netbox environment.

**Comment by DonMusto** [comment]
Thank you, @marcus-crane, but before I got to that level of desperation, it actually worked after enacting @kbcz1989's instruction.

If I knew Git better, I'd suggest an edit to the README.md that includes a point about adding the Azure API Permission "Application\Directory.Read.All" to the application, otherwise you can log in with no issue, but the plug-in cannot read the groups of the user logging in.

Thank you both!

**Comment by marcus-crane** [comment]
Thanks for reporting back and glad to hear it's working :)

Funnily enough, I did add a note about that to the README last night so hopefully others won't run into the same issue

**Comment by DonMusto** [comment]
Awesome!! Thank you for making this plug-in, it really makes a significant impact at my organization.
